### ISSUE TITLE
Constants should appear just like normal methods style

### ISSUE THREAD

**Issue by zzak** [rails/sdoc#211]
Currently constants show the value and any comment description, which can look awkward at times:

![Screenshot 2023-03-22 at 10 57 42](https://user-images.githubusercontent.com/277819/226782294-08a3fcce-26ff-4823-936b-71ba59f27689.png)

![Screenshot 2023-03-22 at 10 59 07](https://user-images.githubusercontent.com/277819/226782355-05196ea9-f096-4de2-90bc-ceeb6a1d601b.png)

---

I think my preference is to have the value be toggleable like the source field is here:

![Screenshot 2023-03-22 at 10 59 41](https://user-images.githubusercontent.com/277819/226782459-53bc57a4-db59-4ccf-b6ba-e1e804c25e9e.png)

Lastly, I'd like to know the effort involved to make them linkable.

**Comment by zzak** [comment]
Another example where the constant value, and description being super confusing to look at:
https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/ContentExfiltrationPreventionHelper.html

<img width="1019" alt="Screenshot 2023-05-30 at 11 25 53" src="https://github.com/rails/sdoc/assets/277819/db58ffff-6240-480b-a604-0a7ba6926a84">

**Comment by p8** [comment]
Fixed by: #356
