### ISSUE TITLE
New header design

### ISSUE THREAD

**Issue by zzak** [rails/sdoc#213]
I would welcome anyone who's interested and wants to try designing a new header for us. Like why is there no Rails logo?

For example, this is what the top of the page looks like fullscreen on my computer:

![Screenshot 2023-03-22 at 11 06 21](https://user-images.githubusercontent.com/277819/226783282-9c534c51-cccd-4cb1-a1df-10564869ea0a.png)

**Comment by hindu-muppala** [comment]
@nickhammond , I want take this issue. I want to add like below image . Is this ok?
![image](https://user-images.githubusercontent.com/120579608/231325516-9f2f5d95-4b55-4a2c-8457-3a3a191ecf90.png)

**Comment by zzak** [comment]
Hey @hindu-muppala, thanks for reaching out and sorry for the delay.

I've just merged #215, but I think we will want to wait on any major changes for now.
