### ISSUE TITLE
Should `attr_reader` and similar be part of the search index?

### ISSUE THREAD

**Issue by Earlopain** [rails/sdoc#369]
As it says in the title.

They are displayed in docs and are similar enough to methods that they probably should?

**Comment by p8** [comment]
I agree, but I think this should probably be fixed upstream in RDoc:
https://edgeguides.rubyonrails.org/active_record_basics.html#validations

**Comment by Earlopain** [comment]
Huh, didn't realize RDoc does the same thing. SDoc has its own logic for that, separate from RDoc (I think). Are you saying RDoc should go first regardless?

**Comment by p8** [comment]
Ah my mistake, I forgot we basically generate the index in SDoc:
https://github.com/rails/sdoc/blob/main/lib/sdoc/search_index.rb
In general, if things can be fixed RDoc, that would have precedence.
We have some monkey patches, but that's not ideal:
https://github.com/rails/sdoc/blob/main/lib/sdoc/rdoc_monkey_patches.rb

**Comment by p8** [comment]
Hmm, we do get the `method_list` from RDoc:
https://github.com/rails/sdoc/blob/242686d0a55cd1f7c1c8b9e96ec85518c5e169a1/lib/sdoc/search_index.rb#L16

Maybe this should be fixed somewhere in RDoc:
https://github.com/ruby/rdoc/blob/7fb0e509ec3f16f636b65d82b286594f87b27d46/lib/rdoc/code_object/context.rb
